fix trigger

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,8 +18,17 @@ jobs:
 
       - name: Check for changes in package.json
         run: |
-          git diff --quiet HEAD^ HEAD -- package.json && echo "No changes in package.json" || exit 1
-
+          if git diff --quiet HEAD^ HEAD -- package.json; then
+            echo "No changes in package.json"
+          else
+            if git diff --quiet HEAD^ HEAD -- ':!package.json'; then
+              echo "Only package.json was changed, aborting"
+              exit 1
+            else
+              echo "Changes in files other than package.json"
+            fi
+          fi
+          
       - name: Use Node.js
         uses: actions/setup-node@v2
         with:
